name: "java_deployment_using_github_action"
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build_test:
        runs-on: ubuntu-latest   # Use ubunutu-latest runner
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
            - name: Build with maven
              run: mvn -B package --file pom.xml

    publish-job:
        runs-on: ubunutu-latest
        needs: build_test
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
            - run: mvn --batch-mode --update-snapshot verify
            - run: mkdir staging && cp target/*.jar staging
            - uses: actions/upload-artifact@v3
              with:
                name: package
                path: staging

    SonarCloudScan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                args: >
                    -Dsonar.organization=aman
                    -Dsonar.projectkey=SonarCloudAnalysis
                    -Dsonar.python.coverage.reportPaths=coverage.xml

    


# Commit Actions
# ls
# git status
# git add.
# git commit -m " new commit "
# git push -u origin main
            